# Generated by Django 5.2.2 on 2025-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProductionCompanies',
            },
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProductionCountries',
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(blank=True, default=False, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('release_date', models.TextField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.FloatField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movie_genre', to='movies.genre')),
                ('production_companies', models.ManyToManyField(blank=True, related_name='movie_production_company', to='movies.productioncompany')),
                ('production_countries', models.ManyToManyField(blank=True, related_name='movie_production_country', to='movies.productioncountry')),
                ('spoken_languages', models.ManyToManyField(blank=True, related_name='movie_spoken_language', to='movies.spokenlanguage')),
            ],
        ),
    ]
