# Generated by Django 5.2.2 on 2025-06-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProductionCompanies',
            },
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProductionCountries',
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(blank=True, default=False, null=True)),
                ('original_language', models.CharField(blank=True, max_length=5, null=True)),
                ('original_title', models.CharField(blank=True, max_length=300, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, max_length=300, null=True)),
                ('video', models.BooleanField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movie_genre', to='movies.genre')),
                ('production_companies', models.ManyToManyField(blank=True, related_name='movie_production_company', to='movies.productioncompany')),
                ('production_countries', models.ManyToManyField(blank=True, related_name='movie_production_country', to='movies.productioncountry')),
                ('spoken_languages', models.ManyToManyField(blank=True, related_name='movie_spoken_language', to='movies.spokenlanguage')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_path', models.CharField(blank=True, max_length=200, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'actor', 'character_name')},
            },
        ),
    ]
