# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: movie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: movie-backend
          image: sathishselvan/movie-backend:v0.3
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: host.docker.internal
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: sathish
            - name: DB_PASSWORD
              value: postgres
            - name: DJANGO_SETTINGS_MODULE
              value: moveibackend.settings.prod
            - name: DJANGO_ENV
              value: prod
          volumeMounts:
            - name: media-volume
              mountPath: /moveibackend/media
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
